### ISSUE TITLE
How do you read in these build files from index.html?

### ISSUE THREAD

**Issue by yongyi520** [shackijj/widget-typescript#9]
I am having trouble reading them in. Am I doing something wrong?

I would create file like below and import file such as index.js from command npm run build:widget

Here's how my html file will look like:
<img width="541" alt="Screenshot 2023-06-05 at 15 42 38" src="https://github.com/preactjs-templates/widget-typescript/assets/10789851/58cf0ad3-dd5e-49e7-b240-449ba0b6edf8">

Here's my output files:
<img width="295" alt="Screenshot 2023-06-05 at 15 42 42" src="https://github.com/preactjs-templates/widget-typescript/assets/10789851/9c0825b1-a446-4fdd-9603-07171868e0a8">

I would get console log error from browser:
<img width="780" alt="Screenshot 2023-06-05 at 15 43 42" src="https://github.com/preactjs-templates/widget-typescript/assets/10789851/e08de1c1-b330-405d-ace5-459447e75f80">

**Comment by rschristian** [comment]
You cannot use CJS in a browser environment, it's inherently Node-only. Use the UMD, ESM, or modern outputs instead.

```html
<script src="./index.umd.js"></script>
```

Might be helpful to read [Microbundle's docs](https://github.com/developit/microbundle).

**Comment by yongyi520** [comment]
Thank you so much!
